### ISSUE TITLE
I can provide a domain for this project

### ISSUE THREAD

**Issue by L33Z22L11** [baozhonger/choose-college-major#1]
I hold the domain `thisis.host` and it will expire in 2031.

So why don't you choose `choice.thisis.host` or so?

**Comment by suenyiyang** [comment]
@L33Z22L11 Thank you for providing your own domain. Currently I'm using domain provided by netlify. For conveniency, I prefer to use the current domain name. I appreciate your effort on providing your help. Both domain names (`thisis.host` and `netlify.app`) are just symbols that unrelated to neither Baoji middle school nor choice 😂. In my view they are just the same.

> BTW, I find it hard for me to allocate my time on this program. Maybe it will not start... 😂
